# Generated by Django 4.0 on 2022-11-12 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='device',
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='patient.patientinfo'),
        ),
    ]
