# Generated by Django 4.0 on 2022-11-12 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patient_device_alter_patient_patient_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
