# Generated by Django 4.0 on 2022-11-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_device_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='crutch',
            field=models.IntegerField(choices=[(0, 'crutch1.png'), (1, 'crutch2.png')], default=0),
        ),
    ]
